services:
  back:
    build: ./back
    container_name: store-back
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env

  front:
    build:
      context: ./front
      args:
        VITE_API_URL: "http://localhost:3000"
    container_name: store-front
    ports:
      - "8080:80"
    depends_on:
      - back